services:
    eos:
        depends_on:
            - msgbus
        image: hardliner66/eos:latest
        volumes:
            - ../workspace:/explore/workspace
        cap_add:
          - SYS_ADMIN

    msgbus:
        image: nats
        command: "--server_name eos_hub --cluster_name EOS --cluster nats://0.0.0.0:6222 --http_port 8222"

volumes:
    storage:
