services:
  eos:
    depends_on:
      - msgbus
    build:
      dockerfile: Dockerfile
    volumes:
      - ../workspace:/explore/workspace
      - storage:/explore/storage
    command: /usr/local/bin/supervisor --force
    network_mode: host

  msgbus:
    image: nats
    command: "--server_name eos_hub --cluster_name EOS --cluster nats://0.0.0.0:6222 --http_port 8222"
    network_mode: host

volumes:
  storage: